---
title: "maternal_health_pad"
author: "queenpanterin2233jol, agens-a"
format: html
editor: visual
---

## Tytuł

---

## EDA

---

```{r}
library(corrplot)
data<-read.csv("mhr_data_set.csv")
data$RiskLevel <- factor(data$RiskLevel, levels = c("low risk", "mid risk", "high risk")) #zmiana na factor ze stringa
#licznosc klas
table(data$RiskLevel) #jest ok
dane_numeryczne <- data[, 1:6]

#robimy korelacje spearmana - nieliniowa i odporna 
macierz_korelacji_s <- cor(dane_numeryczne, method = "spearman")
round(macierz_korelacji_s, 2) 
#brak korelacji
#wizual korelacji
corrplot(macierz_korelacji_s,tl.col = "black",title = "Korelacja Spearmana między predyktorami",mar=c(0,0,2,0))
```

---

```{r}
#przygotowanie danych treningowych i testowych
set.seed(238)
train_index<-sample(1:nrow(data),size=0.7*nrow(data))
train_data<-data[train_index, ]
test_data<-data[-train_index, ]




#analiza glownych skladowych (PCA)
pca_model <- prcomp(train_data[,1:6], center = TRUE, scale. = TRUE)
summary(pca_model)
plot(pca_model, type = "lines", main="Wykres osypiskowy")
#sprawdzamy czy jest kwadratowa (macierz ladunkow) - OK
nrow(pca_model$rotation) == ncol(pca_model$rotation)

#zabezpieczamy numerycznie
pca_model$rotation %*% t(pca_model$rotation) |> round()

#sprawdzamy czy dane sa ustandaryzowane - sumujemy ich odchylenia standardowe, a powinny wynosic tyle ile jest atrybutow 
sum(pca_model$sdev^2)

library(factoextra)
fviz_pca_biplot(pca_model,geom.ind="point",repel=TRUE,legend.title="Poziom ryzyka",title="PCA Biplot - Struktura zbioru treningowego")
```

Redukcja wymiarow
```{r}
train_pca <- data.frame(pca_model$x[,1:5])
train_pca$RiskLevel <- train_data$RiskLevel

test_pca_values <- predict(pca_model, newdata = test_data[, 1:6])
test_pca <- data.frame(test_pca_values[, 1:5])
test_pca$RiskLevel <- test_data$RiskLevel
```
